graphql:
  servlet:
    mapping: /graphql

#keycloak:
#  auth-server-url: http://localhost:8085/auth/realm/myrealm/account
#  realm: myrealm
#  resource: login-app
#  public-client: true
#  security-constraints[0]:
#    authRoles[0]: user
#    securityCollections[0]:
#      patterns[0]: /graphql